addressbook/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import contacts.views
from django.core.urlresolvers import reverse, reverse_lazy
from contacts.models import Contact

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'addressbook.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', contacts.views.ListContactView.as_view(), name='contacts-list',),
    # url(r'^new$', contacts.views.CreateContactView.as_view(), name='contacts-new',),
    url(r'^new$', contacts.views.CreateContactView.as_view(model=Contact, success_url=reverse_lazy('contacts-list')), name='contacts-new',),
    url(r'^edit/(?P<pk>\d+)/$', contacts.views.UpdateContactView.as_view(model=Contact, success_url=reverse_lazy('contacts-list')), name='contacts-edit'),
    url(r'^delete/(?P<pk>\d+)/$', contacts.views.DeleteContactView.as_view(model=Contact, success_url=reverse_lazy('contacts-list')), name='contacts-delete'),
    url(r'^(?P<pk>\d+)/$', contacts.views.ContactView.as_view(), name='contacts-view'),
    url(r'^edit/(?P<pk>\d+)/address/$', contacts.views.EditContactAddressView.as_view(), name='contacts-edit-addresses', ),
)

contacts/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Contact(models.Model):

    first_name = models.CharField(max_length=255,)
    last_name = models.CharField(max_length=255,)
    middle_name = models.CharField(max_length=255,)

    email = models.EmailField()

    def __str__(self):
        return ' '.join([self.first_name,self.last_name,self.middle_name,])

    def get_absolute_url(self):
        return reverse('contacts-view', kwargs={'pk': self.id})

class Address(models.Model):

    contact = models.ForeignKey(Contact)
    address_type = models.CharField(max_length=10,)
    address = models.CharField(max_length=255,)
    city = models.CharField(max_length=255,)
    state = models.CharField(max_length=2,)
    postal_code = models.CharField(max_length=20,)

    class Meta:
        unique_together = ('contact', 'address_type',)

contacts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.models import inlineformset_factory

from contacts.models import (Contact, Address, )

# inlineformset_factory creates a Class from a parent model (Contact)
# to a child model (Address)
ContactAddressFormSet = inlineformset_factory(Contact, Address, )

class ContactForm(forms.ModelForm):

    confirm_email = forms.EmailField(
        label="Confirm email",
        required=True,
    )

    class Meta:
        model = Contact

    def __init__(self, *args, **kwargs):
        if kwargs.get('instance'):
            email = kwargs['instance'].email
            kwargs.setdefault('initial', {})['confirm_email'] = email

        return super(ContactForm, self).__init__(*args, **kwargs)

    def clean(self):
        if (self.cleaned_data.get('email') !=
            self.cleaned_data.get('confirm_email')):

            raise ValidationError("Email addresses must match!")

        return self.cleaned_data

contacts/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.core.urlresolvers import reverse, reverse_lazy
from contacts.models import Contact
import forms

class ListContactView(ListView):
    model = Contact
    template_name = 'contact_list.html'

class CreateContactView(CreateView):
    model = Contact
    template_name = 'edit_contact.html'
    form_class = forms.ContactForm

    # def get_successful_url(self):
        # return reverse_lazy('contacts-list')

    def get_context_data(self, **kwargs):
        context = super(CreateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts-new')
        return context

class UpdateContactView(UpdateView):
    model = Contact
    template_name = 'edit_contact.html'
    form_class = forms.ContactForm

    # def get_successful_url(self):
        # return reverse_lazy('contacts-list')

    def get_context_data(self, **kwargs):
        context = super(UpdateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts-edit', kwargs={'pk': self.get_object().id})
        return context

class DeleteContactView(DeleteView):
    model = Contact
    template_name = 'delete_contact.html'

    # def get_success_url(self):
        # return reverse('contacts-list')

class ContactView(DetailView):
    model = Contact
    template_name = 'contact.html'

class EditContactAddressView(UpdateView):
    model = Contact
    template_name = 'edit_address.html'
    form_class = forms.ContactAddressFormSet

    def get_success_url(self):
        # redirect to the Contact view.
        return self.get_object().get_absolute_url()

contacts/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Example of Twitter Bootstrap 3 Grid System</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}" media="screen">
  </head>
  <body>
    {% block content %}
    {% endblock %}

    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

contacts/templates/contact.html
{% extends "base.html" %}

{% block content %}

<h1>{{ contact }}</h1>

<p>Email: {{ contact.email }}</p>

<ul>
{% for address in contact.address_set.all %}
    <li>{% if address.address %}
            {{ address.address }} <br />
        {% endif %}
        {{ address.city }} {{ address.state }} <br />
        {{ address.postal_code }}
    </li>
{% endfor %}
</ul>

{% endblock %}

contacts/templates/contact_list.html
{% extends "base.html" %}

{% block content %}
<h1>Contacts</h1>

<ul>
  {% for contact in object_list %}
    <li class="contact">
        <a href="{{ contact.get_absolute_url }}">{{ contact }}</a>
        (<a href="{% url "contacts-edit" pk=contact.id %}">edit</a>)
    </li>
  {% endfor %}
</ul>

<!-- <a href="{% url "contacts-new" %}">add contact</a> -->
<a href="{% url "contacts-new" %}" class="btn btn-success btn-sm">add contact <span class="glyphicon glyphicon-edit"></span></a>
{% endblock %}

contacts/templates/delete_contact.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Contact</h1>

<p>Are you sure you want to delete the contact {{ contact }}?</p>

<form action="{% url 'contacts-delete' pk=contact.id %}" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, delete.">
    <a href="{% url 'contacts-list' %}">No, cancel</a>
</form>

{% endblock %}

contacts/templates/edit_address.html
{% extends "base.html" %}

{% block content %}

<h1>Edit Addresses</h1>

<p>Editing addresses for {{ contact }}</p>

<form action="{% url "contacts-edit-addresses" pk=contact.id %}"
      method="POST">
    {% csrf_token %}
    {{ form.management_form }}
    {% for address_form in form %}

        <ul>
        {{ address_form.as_ul }}
        </ul>

    {% endfor %}

    <input type="submit" value="Save" />
</form>

{% endblock %}

contacts/templates/edit_contact.html
{% extends "base.html" %}
{% block content %}

{% if contact.id %}
    <h1>Edit Contact</h1>
{% else %}
    <h1>Add Contact</h1>
{% endif %}

<form action="{{ action }}" method="POST">
  {% csrf_token %}
  {% if form.non_field_errors %}
    <ul>
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% for field in form %}
  <div id="{{ field.auto_id }}_container">
    {{ field.help_text }}
    <div>
      {{ field.label_tag }} {{ field }}
    </div>
    <div id="{{ field.auto_id }}_errors">
      {{ field.errors }}
    </div>
  </div>
  {% endfor %}

  <input id="save_contact" type="submit" value="Save" />
</form>

{% if contact.id %}
    <a href="{% url "contacts-delete" pk=contact.id %}">Delete</a>
{% endif %}

<a href="{% url "contacts-list" %}">back to list</a>

{% endblock %}

contacts/templates/test.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Example of Twitter Bootstrap 3 Grid System</title>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <style type="text/css">
            p{
                padding: 50px;
                font-size: 32px;
                font-weight: bold;
                text-align: center;
                background: #f2f2f2;
            }
        </style>
    </head>
    <body>
        <div class="container">
		    <div class="row">
		        <div class="col-md-4"><p>Box 1</p></div>
		        <div class="col-md-4"><p>Box 2</p></div>
		        <div class="col-md-4"><p>Box 3</p></div>
		        <div class="clearfix visible-md-block"></div>
		        <div class="col-md-4"><p>Box 4</p></div>
		        <div class="col-md-4"><p>Box 5</p></div>
		        <div class="col-md-4"><p>Box 6</p></div>
		        <div class="clearfix visible-md-block"></div>
		        <div class="col-md-4"><p>Box 7</p></div>
		        <div class="col-md-4"><p>Box 8</p></div>
		        <div class="col-md-4"><p>Box 9</p></div>
		        <div class="clearfix visible-md-block"></div>
		        <div class="col-md-4"><p>Box 10</p></div>
		        <div class="col-md-4"><p>Box 11</p></div>
		        <div class="col-md-4"><p>Box 12</p></div>
		    </div>
		</div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    </body>
</html>                                         

contacts/templates/test_2.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Example of Twitter Bootstrap 3 Grid System</title>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    </head>
    <body>
    <nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Tutorial Republic</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="http://www.tutorialrepublic.com" target="_blank">Home</a></li>
                    <li><a href="http://www.tutorialrepublic.com/about-us.php" target="_blank">About</a></li>
                    <li><a href="http://www.tutorialrepublic.com/contact-us.php" target="_blank">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="jumbotron">
            <h1>Learn to Create Websites</h1>
            <p>In today's world internet is the most popular way of connecting with the people. At <a href="http://www.tutorialrepublic.com" target="_blank">tutorialrepublic.com</a> you will learn the essential of web development technologies along with real life practice example, so that you can create your own website to connect with the people around the world.</p>
            <p><a href="http://www.tutorialrepublic.com" target="_blank" class="btn btn-success btn-lg">Get started today</a></p>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-4 col-lg-2">
                <h2>HTML</h2>
                <p>HTML is a markup language that is used for creating web pages. The HTML tutorial section will help you understand the basics of HTML, so that you can create your own web pages or website.</p>
                <p><a href="http://www.tutorialrepublic.com/html-tutorial/" target="_blank" class="btn btn-success btn-medium">Learn More &raquo;</a></p>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-2">
                <h2>CSS</h2>
                <p>CSS is used for describing the presentation of web pages. The CSS tutorial section will help you learn the essentials of CSS, so that you can fine control the style and layout of your HTML document.</p>
                <p><a href="http://www.tutorialrepublic.com/css-tutorial/" target="_blank" class="btn btn-success btn-medium">Learn More &raquo;</a></p>
            </div>
            <div class="clearfix visible-sm-block"></div>
            <div class="col-sm-6 col-md-4 col-lg-2">
                <h2>Bootstrap</h2>
                <p>Twitter Bootstrap is a powerful front-end framework for faster and easier web development. The Twitter Bootstrap tutorial section will help you learn the techniques of Bootstrap so that you can create web your own website with much less efforts.</p>
                <p><a href="http://www.tutorialrepublic.com/twitter-bootstrap-tutorial/" target="_blank" class="btn btn-success btn-medium">Learn More &raquo;</a></p>
            </div>
            <div class="clearfix visible-md-block"></div>
            <div class="col-sm-6 col-md-4 col-lg-2">
                <h2>References</h2>
                <p>The references section outlines all the standard HTML tags and CSS properties along with other useful references such as color names and values, symbols and character entities, web safe fonts, language codes, HTTP messages and much more.</p>
                <p><a href="http://www.tutorialrepublic.com/twitter-bootstrap-tutorial/" target="_blank" class="btn btn-success btn-medium">Learn More &raquo;</a></p>
            </div>
            <div class="clearfix visible-sm-block"></div>
            <div class="col-sm-6 col-md-4 col-lg-2">
                <h2>Examples</h2>
                <p>The examples section encloses an extensive collection of examples on various topic that you can try and test yourself using online HTML editor.</p>
                <p><a href="http://www.tutorialrepublic.com/twitter-bootstrap-tutorial/" target="_blank" class="btn btn-success btn-medium">Learn More &raquo;</a></p>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-2">
                <h2>FAQ</h2>
                <p>The collection of Frequently Asked Questions (FAQ) provides brief answers to many common questions related to web design and development.</p>
                <p><a href="http://www.tutorialrepublic.com/twitter-bootstrap-tutorial/" target="_blank" class="btn btn-success btn-medium">Learn More &raquo;</a></p>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-12">
                <footer>
                    <p>&copy; Copyright 2013 Tutorial Republic</p>
                </footer>
            </div>
        </div>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    </body>
</html>                                      